spring.application.name=sercop_ingestion_service
spring.datasource.url=jdbc:postgresql://localhost:5432/sercop_db
spring.datasource.username=ismaeln
spring.datasource.password=123456
spring.jpa.hibernate.ddl-auto=update
spring.servlet.multipart.max-file-size=150MB
spring.servlet.multipart.max-request-size=150MB
