sercop:
  ingesta:
    max-reintentos: 3
    espera-inicial: 2000

spring:
  jpa:
    show-sql: false
    properties:
      hibernate:
        jdbc:
          batch_size: 50
        order_inserts: true
        order_updates: true

logging:
  level:
    org.hibernate.SQL: OFF
    org.hibernate.orm.jdbc.bind: OFF